services:
  pronote-rest:
    container_name: pronote-rest
    build: .
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./config:/home/node/config
      - ./screenshot:/home/node/screenshot
