version: "3"
services:
  pronote-rest:
    container_name: pronote-rest
    image: bdbogjoe/pronote-rest:master
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./config:/home/app/config
